services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: spot-down-db-password  # Add the password here
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis 
      - rabbitmq
    volumes:
      - ./songs:/app/songs

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: spot-down-db-password
    ports:
      - "5002:5002"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./songs:/app/songs
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: spot-down-db-password
      POSTGRES_DB: spotdowndb  # Ensure this matches your connection config
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./postgres-init:/docker-entrypoint-initdb.d  # Mount the SQL script
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
  songs:
